const APP_VERSION=35;
const API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-multi-api';
const ADMIN_REFRESH_API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-admin-refresh';
const TOKEN_KEY='kokmatch_token',GROUP_KEY='kokmatch_group_id',REFRESH_KEY='kokmatch_refresh_state';
let T=localStorage.getItem(TOKEN_KEY)||'',S=emptyClientState(),me=null,group=null,groups=[],groupSummaries=[];
let currentGroupId=localStorage.getItem(GROUP_KEY)||'',currentView='members',draft=[null,null,null,null],editMemberId=null;
let pendingLoginName='',pendingLoginPin='',moveCtx=null,courtCtx=null,repeatCtx=null,reloginBusy=false;
const $=id=>document.getElementById(id),M=id=>S.members.find(m=>m.id===id);
function emptyClientState(){return{courtCount:8,courtNames:[],members:[],queue:[],pendingGames:[],games:[],history:[],pairCounts:{}}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function todayKst(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function roleOf(m){const r=String(m?.role||'member');return r==='manager'||r==='organizer'?r:r==='admin'?'admin':'member'}
function roleLabel(r){return r==='admin'?'총관리자':r==='manager'?'모임관리자':r==='organizer'?'게임편성자':'일반회원'}
function stateLabel(s){return s==='waiting'?'게임대기':s==='matched'?'편성대기':s==='playing'?'게임중':s==='spectator'?'관람':'미입장'}
function isTemp(m){return !!m&&roleOf(m)==='member'&&m.type!=='guest'&&m.state!=='out'&&String(m.tempOrganizerDay||'')===todayKst()}
function canGame(){return !!me&&(me.globalAdmin||me.role==='manager'||me.role==='organizer'||me.tempOrganizer)}
function canManageMembers(){return !!me&&(me.globalAdmin||me.role==='manager'||me.role==='organizer')}
function canSetRoles(){return !!me&&(me.globalAdmin||me.role==='manager')}
function canReset(){return !!me&&(me.globalAdmin||me.role==='manager')}
function canManageGroups(){return !!me?.globalAdmin}
function roleBadge(m){let r=roleOf(m);if(r==='admin'||(me?.globalAdmin&&m?.name===me.displayName))return '<span class="roleBadge role-global">총관리자</span>';if(r==='manager')return '<span class="roleBadge role-manager">모임관리자</span>';if(r==='organizer')return '<span class="roleBadge role-organizer">게임편성자</span>';if(isTemp(m))return '<span class="roleBadge role-temp">임시편성자</span>';return ''}
function typeBadge(m){return m?.type==='guest'?'<span class="roleBadge guest">GUEST</span>':''}
function ageTag(m){return '<span class="tag">'+esc(m?.age||'30')+esc(m?.cls||'C')+'</span>'}
function dailyCount(id){return S.history.filter(h=>Array.isArray(h.players)&&h.players.includes(id)).length}
function waitMins(m){return Math.max(0,Math.floor((Date.now()-(Number(m?.joinedAt)||Date.now()))/60000))}
function pairKey(a,b){return a<b?a+'|'+b:b+'|'+a}
function pairCount(a,b){return Math.max(0,Number(S.pairCounts?.[pairKey(a,b)])||0)}
function avatar(m){return '<div class="avatar '+(m?.gender==='여'?'female':'male')+'">●</div>'}
function normalizeClient(){S=S||emptyClientState();S.members=Array.isArray(S.members)?S.members:[];S.queue=Array.isArray(S.queue)?S.queue:[];S.pendingGames=Array.isArray(S.pendingGames)?S.pendingGames:[];S.games=Array.isArray(S.games)?S.games:[];S.history=Array.isArray(S.history)?S.history:[];S.pairCounts=S.pairCounts||{};S.courtCount=Math.max(1,Number(S.courtCount)||8);S.courtNames=Array.from({length:S.courtCount},(_,i)=>String(S.courtNames?.[i]||`${i+1}코트`));draft=draft.map(id=>id&&S.queue.includes(id)?id:null)}
function renderShell(){document.body.innerHTML=`<div id="login" class="login"><div class="loginBox" id="loginBox"></div></div><div class="app"><header class="top"><div class="toprow"><div><div class="brand">🏸 콕매치</div><div class="groupLine"><button id="groupBtn" class="groupBtn" onclick="openGroupSwitch()">모임 선택</button></div><div id="who" class="who">-</div></div><button class="logout" onclick="logout()">로그아웃</button></div><div class="summary"><div><b id="sm">0</b><span>오늘 입장</span></div><div><b id="sw">0</b><span>게임대기</span></div><div><b id="sg">0</b><span>게임중</span></div></div></header><main><section id="members" class="view on"></section><section id="queue" class="view"></section><section id="playing" class="view"></section><section id="stats" class="view"></section><section id="settings" class="view"></section><section id="groups" class="view"></section></main></div><nav id="nav"></nav><div id="modal" class="modal"><div class="sheet" id="modalSheet"></div></div>`;renderLoginName();renderNav()}
function renderNav(){const items=[['members','👥','회원명부'],['queue','▦','게임대기'],['playing','🏸','게임중'],['stats','▥','오늘통계'],['settings','⚙️','설정']];if(canManageGroups())items.push(['groups','🏢','모임관리']);const n=$('nav');if(!n)return;n.className='n'+items.length;n.innerHTML=items.map(([id,ic,tx])=>`<button data-v="${id}" class="${currentView===id?'on':''}" onclick="goView('${id}')"><i>${ic}</i>${tx}</button>`).join('')}
function goView(id){if(id==='groups'&&!canManageGroups())id='members';currentView=id;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('on',v.id===id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('on',b.dataset.v===id));if(id==='groups')loadGroups().catch(showError);window.scrollTo(0,0)}
function openModal(html){$('modalSheet').innerHTML=html;$('modal').classList.add('on')}
function closeModal(){$('modal').classList.remove('on');$('modalSheet').innerHTML='';moveCtx=null;courtCtx=null}
function showError(e){alert(e?.message||String(e||'오류가 발생했습니다.'))}
async function reloginLatest(){if(reloginBusy)return;reloginBusy=true;localStorage.removeItem(TOKEN_KEY);T='';try{if('caches'in window){const ks=await caches.keys();await Promise.all(ks.map(k=>caches.delete(k)))}if('serviceWorker'in navigator){const rs=await navigator.serviceWorker.getRegistrations();await Promise.all(rs.map(r=>r.unregister().catch(()=>{})))}}catch{}location.replace('/?relogin='+Date.now())}
async function request(apiName,method='GET',body=null,params={}){const u=new URL(API);u.searchParams.set('api',apiName);Object.entries(params).forEach(([k,v])=>{if(v)u.searchParams.set(k,v)});const r=await fetch(u,{method,headers:{'content-type':'application/json',...(T?{authorization:'Bearer '+T}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const x=await r.json().catch(()=>({error:'통신 오류'}));if(!r.ok){if(r.status===401&&apiName!=='login'&&apiName!=='login_probe'){reloginLatest();throw new Error('로그인이 만료되었습니다.')}const e=new Error(x.error||'오류가 발생했습니다.');e.payload=x;throw e}return x}
function renderLoginName(){$('loginBox').innerHTML=`<h1>🏸 콕매치</h1><div class="meta" style="font-size:14px;margin-bottom:18px">모임 회원 로그인</div><div class="field"><label>등록된 이름</label><input id="loginName" autocomplete="username" placeholder="이름"></div><button class="btn pri" style="width:100%" onclick="startLogin()">다음</button><div id="loginErr" class="error"></div><div class="note" style="margin-top:12px">일반회원은 <b>소속 모임 PIN</b>, 모임관리자·게임편성자는 <b>본인 역할 PIN</b>으로 로그인합니다.</div>`;setTimeout(()=>$('loginName')?.focus(),50)}
async function startLogin(){const name=$('loginName').value.trim();$('loginErr').textContent='';if(!name)return $('loginErr').textContent='이름을 입력해주세요.';try{const x=await request('login_probe','POST',{name});pendingLoginName=name;$('loginBox').innerHTML=`<h2>${esc(x.roleLabel||'PIN')} 인증</h2><div class="authName">${esc(name)}</div><div class="field"><label>PIN</label><input id="loginPin" type="password" inputmode="numeric" placeholder="PIN 입력"></div><button class="btn pri" style="width:100%" onclick="submitLogin()">로그인</button><div id="loginErr" class="error"></div><button class="btn ghost" style="width:100%;margin-top:8px" onclick="renderLoginName()">← 이름 다시 입력</button>`;setTimeout(()=>$('loginPin')?.focus(),50)}catch(e){$('loginErr').textContent=e.message}}
async function submitLogin(groupId=''){const pin=$('loginPin')?.value.trim()||pendingLoginPin;if(!pin)return $('loginErr').textContent='PIN을 입력해주세요.';pendingLoginPin=pin;try{const x=await request('login','POST',{name:pendingLoginName,pin,groupId});if(x.groupChoiceRequired){$('loginBox').innerHTML=`<h2>모임 선택</h2><div class="authName">${esc(pendingLoginName)}</div><div class="note">같은 PIN으로 확인되는 모임이 여러 개입니다. 접속할 모임을 선택해주세요.</div><div class="choiceList">${x.choices.map(c=>`<button class="choiceBtn" onclick="submitLogin('${c.groupId}')"><b>${esc(c.groupName)}</b><span class="meta">${esc(c.roleLabel)}</span></button>`).join('')}</div><button class="btn ghost" style="width:100%;margin-top:9px" onclick="renderLoginName()">처음으로</button>`;return}T=x.token;localStorage.setItem(TOKEN_KEY,T);if(x.groupId){currentGroupId=x.groupId;localStorage.setItem(GROUP_KEY,currentGroupId)}$('login').classList.add('hide');pendingLoginPin='';await loadState();const mine=me.memberId?M(me.memberId):null;if(mine?.state==='out')openEntry()}catch(e){const el=$('loginErr');if(el)el.textContent=e.message;else alert(e.message)}}
async function logout(){try{await request('logout','POST')}catch{}localStorage.removeItem(TOKEN_KEY);T='';location.replace('/')}
async function loadState(){const x=await request('state','GET',null,{groupId:currentGroupId});S=x.data;me=x.user;group=x.group;groups=x.groups||groups;currentGroupId=group.groupId;localStorage.setItem(GROUP_KEY,currentGroupId);normalizeClient();renderAll();restoreRefreshState()}
async function act(action,body={},opts={}){try{const x=await request('action','POST',{action,groupId:currentGroupId,...body});if(x.data){S=x.data;normalizeClient();renderAll()}return x}catch(e){if(e.payload?.warning==='repeat_pair'&&opts.repeat){showRepeat(e.payload,opts.repeat);return null}throw e}}
function renderAll(){if(!me)return;renderHeader();renderNav();renderMembers();renderQueue();renderPlaying();renderStats();renderSettings();if(canManageGroups()&&currentView==='groups')renderGroups();document.querySelectorAll('.view').forEach(v=>v.classList.toggle('on',v.id===currentView));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('on',b.dataset.v===currentView))}
function renderHeader(){const mine=me.memberId?M(me.memberId):null;$('groupBtn').textContent=(group?.name||'모임')+(me.globalAdmin?' ▾':'');$('groupBtn').disabled=!me.globalAdmin;$('who').textContent=`${me.displayName} · ${roleLabel(me.role)}${me.tempOrganizer?' · 임시편성자':''}${mine?' · '+stateLabel(mine.state):''}`;$('sm').textContent=S.members.filter(m=>m.state!=='out').length;$('sw').textContent=S.queue.length+S.pendingGames.reduce((n,g)=>n+g.players.length,0);$('sg').textContent=S.games.length}
function memberControls(m){if(!canManageMembers())return `<div class="status">${stateLabel(m.state)}</div>`;const r=roleOf(m);let editable=me.globalAdmin||(me.role==='manager'?(r!=='manager'||m.id===me.memberId):r==='member');let bs='';if(m.state!=='playing'&&m.state!=='matched'){if(m.state!=='waiting')bs+=`<button class="btn enter" onclick="setOther('${m.id}','waiting')">운동</button>`;if(m.state!=='spectator')bs+=`<button class="btn watch" onclick="setOther('${m.id}','spectator')">관람</button>`;if(m.state!=='out')bs+=`<button class="btn danger" onclick="setOther('${m.id}','out')">퇴장</button>`}if(editable)bs+=`<button class="btn ghost" onclick="openEditMember('${m.id}')">수정</button>`;return `<div><div class="status">${stateLabel(m.state)}</div><div class="memberBtns">${bs}</div></div>`}
function renderMembers(){const note=me.globalAdmin?'총관리자는 현재 모임의 모든 인원과 역할을 관리할 수 있습니다.':me.role==='manager'?'모임관리자는 일반회원 관리와 게임편성자 지정·해제가 가능합니다.':me.role==='organizer'?'게임편성자는 소속 모임의 일반회원/게스트를 등록·수정·삭제할 수 있습니다.':'회원정보와 현재 참가상태를 확인할 수 있습니다.';$('members').innerHTML=`<div class="title"><h2>회원명부</h2>${canManageMembers()?'<button class="btn pri" onclick="openAddMember()">+ 회원등록</button>':''}</div><div class="note">${note}</div><div>${S.members.map(m=>`<div class="card memberCard">${avatar(m)}<div><div class="name">${esc(m.name)} ${ageTag(m)} ${typeBadge(m)} <span class="gamecnt">총 게임 ${Number(m.totalGames)||0}회</span> ${roleBadge(m)}</div><div class="meta">${esc(m.year||'')}년생 · ${esc(m.gender||'')}</div><button class="pairBtn" onclick="openPairs('${m.id}')">같이한 경기 보기</button></div>${memberControls(m)}</div>`).join('')||'<div class="empty">등록된 회원이 없습니다.</div>'}</div>`}
function openAddMember(){editMemberId=null;openMemberModal(null)}
function openEditMember(id){const m=M(id);if(!m)return;editMemberId=id;openMemberModal(m)}
function openMemberModal(m){const add=!m;const role=roleOf(m);const roleOptions=me.globalAdmin?['member','organizer','manager']:me.role==='manager'?['member','organizer']:[];openModal(`<h3>${add?'회원등록':'회원 정보 수정'}</h3><div class="note">${add?'출생연도를 입력하면 연령대가 자동 설정됩니다.':'회원정보와 권한을 수정합니다.'}</div><div class="field"><label>이름</label><input id="fmName" value="${esc(m?.name||'')}"></div><div class="grid2"><div class="field"><label>출생연도</label><input id="fmYear" type="number" inputmode="numeric" value="${esc(m?.year||'')}"></div><div class="field"><label>성별</label><select id="fmGender"><option ${m?.gender!=='여'?'selected':''}>남</option><option ${m?.gender==='여'?'selected':''}>여</option></select></div><div class="field"><label>연령대</label><select id="fmAge">${[20,30,40,50,60,70].map(a=>`<option value="${a}" ${String(m?.age||'30')===String(a)?'selected':''}>${a}대</option>`).join('')}</select></div><div class="field"><label>급수</label><select id="fmCls">${['A','B','C','D','E'].map(c=>`<option ${String(m?.cls||'C')===c?'selected':''}>${c}</option>`).join('')}</select></div></div><div class="field"><label>구분</label><select id="fmType"><option value="member" ${m?.type!=='guest'?'selected':''}>일반회원</option><option value="guest" ${m?.type==='guest'?'selected':''}>게스트</option></select></div>${!add&&roleOptions.length?`<div class="field"><label>역할</label><select id="fmRole" onchange="syncRolePinField()">${roleOptions.map(r=>`<option value="${r}" ${role===r?'selected':''}>${roleLabel(r)}</option>`).join('')}</select></div><div id="fmPinWrap" class="field ${role==='member'?'hide':''}"><label>새 역할 PIN (변경 시 숫자 4~8자리)</label><input id="fmPin" type="password" inputmode="numeric" placeholder="기존 PIN 유지 시 비움"></div>`:''}<div class="acts">${!add?'<button class="btn danger" onclick="deleteMemberNow()">삭제</button>':''}<button class="btn ghost" onclick="closeModal()">취소</button><button class="btn pri" onclick="saveMemberNow()">${add?'등록':'저장'}</button></div>`);setTimeout(()=>{const y=$('fmYear');if(y)y.addEventListener('input',()=>{const year=Number(y.value);if(year>1900){const age=Math.max(10,Math.floor((new Date().getFullYear()-year)/10)*10);$('fmAge').value=String(Math.min(70,age))}})},0)}
function syncRolePinField(){const r=$('fmRole')?.value;$('fmPinWrap')?.classList.toggle('hide',!r||r==='member')}
async function saveMemberNow(){const body={name:$('fmName').value.trim(),year:Number($('fmYear').value),gender:$('fmGender').value,age:$('fmAge').value,cls:$('fmCls').value,type:$('fmType').value};if(!body.name)return alert('이름을 입력해주세요.');try{if(!editMemberId){await act('add_member',body);closeModal();return}const m=M(editMemberId),oldRole=roleOf(m);await act('edit_member',{memberId:editMemberId,...body});const nr=$('fmRole')?.value;if(nr&&nr!==oldRole){await act('set_role',{memberId:editMemberId,role:nr,pin:$('fmPin')?.value.trim()||''})}else if(nr&&nr!=='member'&&$('fmPin')?.value.trim()){await act('set_role',{memberId:editMemberId,role:nr,pin:$('fmPin').value.trim()})}closeModal()}catch(e){showError(e)}}
async function deleteMemberNow(){const m=M(editMemberId);if(!m||!confirm(`${m.name} 회원을 삭제하시겠습니까?`))return;try{await act('delete_member',{memberId:editMemberId});closeModal()}catch(e){showError(e)}}
async function setOther(id,mode){try{await act('set_member_attendance',{memberId:id,mode})}catch(e){showError(e)}}
function openEntry(){openModal(`<h3>오늘 어떻게 입장할까요?</h3><div class="note">역할과 운동 참여 여부는 별개입니다.</div><div class="acts"><button class="btn enter" onclick="setMyEntry('waiting')">🏸 운동 참가</button><button class="btn watch" onclick="setMyEntry('spectator')">👀 관람하기</button></div><button class="btn ghost" style="width:100%;margin-top:9px" onclick="closeModal()">입장 없이 보기</button>`)}
async function setMyEntry(mode){try{await act('set_my_attendance',{mode});closeModal();if(mode==='waiting')goView('queue')}catch(e){showError(e)}}
function sortedQueue(){return S.queue.slice().sort((a,b)=>dailyCount(a)-dailyCount(b)||(Number(M(a)?.joinedAt)||Infinity)-(Number(M(b)?.joinedAt)||Infinity))}
function draftClick(id){if(!canGame())return;const idx=draft.indexOf(id);if(idx>=0)draft[idx]=null;else{const e=draft.findIndex(x=>!x);if(e>=0)draft[e]=id}renderQueue()}
function draftRemove(i){draft[i]=null;renderQueue()}
function clearDraft(){draft=[null,null,null,null];renderQueue()}
function pairSummary(ids){let total=0,max=0,pair='';for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const n=pairCount(ids[i],ids[j]);total+=n;if(n>max){max=n;pair=`${M(ids[i])?.name||'-'}·${M(ids[j])?.name||'-'}`}}return ids.length<2?'':total?`같이한 경기 합계 ${total}회${max?` · 최다 ${pair} ${max}회`:''}`:'서로 같이한 경기 기록이 없습니다.'}
const gradeV={A:5,B:4,C:3,D:2,E:1};
function recommendDraft(){const pool=sortedQueue().filter(id=>!draft.includes(id)).slice(0,24);if(pool.length<4)return alert('개인 게임대기 인원이 4명 이상 필요합니다.');let best=null,score=Infinity;for(let a=0;a<pool.length-3;a++)for(let b=a+1;b<pool.length-2;b++)for(let c=b+1;c<pool.length-1;c++)for(let d=c+1;d<pool.length;d++){const ids=[pool[a],pool[b],pool[c],pool[d]],ms=ids.map(M),gv=ms.map(m=>gradeV[m?.cls]||1),mean=gv.reduce((x,y)=>x+y,0)/4,variance=gv.reduce((x,y)=>x+(y-mean)**2,0),male=ms.filter(m=>m?.gender==='남').length;let repeat=0;for(let i=0;i<4;i++)for(let j=i+1;j<4;j++)repeat+=pairCount(ids[i],ids[j]);const s=repeat*18+variance*7+Math.abs(male-2)*10+a*.02;if(s<score){score=s;best=ids}}draft=best;renderQueue()}
async function registerDraft(forceRepeat=false){const ps=draft.filter(Boolean);if(!ps.length)return alert('1명 이상 선택해주세요.');if(ps.length<4&&!confirm(`현재 ${ps.length}명입니다. 4명이 안 됐는데 편성대기로 등록하시겠습니까?`))return;try{const x=await act('create_pending',{players:ps,forceRepeat},{repeat:{keep:()=>registerDraft(true),manual:()=>{clearDraft();closeModal()},recommend:()=>{closeModal();clearDraft();recommendDraft()}}});if(x){draft=[null,null,null,null];renderQueue()}}catch(e){showError(e)}}
function showRepeat(payload,ctx){repeatCtx=ctx;openModal(`<h3>반복 편성 확인</h3><div class="warn">3회 이상 같이 경기한 조합이 있습니다.</div>${(payload.repeatPairs||[]).map(r=>`<div class="card"><b>${esc(r.aName)} · ${esc(r.bName)}</b><span class="tag">${r.count}회</span></div>`).join('')}<div class="acts">${ctx.manual?'<button class="btn ghost" onclick="repeatManual()">다시 직접 편성</button>':''}${ctx.recommend?'<button class="btn ghost" onclick="repeatRecommend()">추천으로 다시</button>':''}<button class="btn pri" onclick="repeatKeep()">그대로 진행</button></div>`)}
function repeatKeep(){const f=repeatCtx?.keep;closeModal();repeatCtx=null;f?.()}
function repeatManual(){const f=repeatCtx?.manual;closeModal();repeatCtx=null;f?.()}
function repeatRecommend(){const f=repeatCtx?.recommend;closeModal();repeatCtx=null;f?.()}
function pendingCard(pg,i){const waited=Math.max(0,Math.floor((Date.now()-Number(pg.createdAt||Date.now()))/60000));const slots=Array.from({length:4},(_,idx)=>{const id=pg.players[idx],m=id?M(id):null;if(!m)return `<div class="pendingSlot emptySlot ${canGame()?'clickable':''}" ${canGame()?`onclick="openFillPending('${pg.id}')"`:''}>＋ 빈자리</div>`;return `<div class="pendingSlot ${canGame()?'clickable':''}" ${canGame()?`onclick="openMoveMember('${pg.id}','${id}')"`:''}>${canGame()?`<button class="pendingX" onclick="event.stopPropagation();removePending('${pg.id}','${id}')">×</button>`:''}<div class="slotLabel">${idx<2?'A팀':'B팀'} ${idx%2+1}</div><div class="slotName">${esc(m.name)} ${ageTag(m)} ${roleBadge(m)}</div><div class="meta">게임 ${dailyCount(id)}회 · ${waitMins(m)}분 대기</div></div>`}).join('');return `<div class="card pendingCard"><div class="pendingHead"><b>편성대기 ${i+1}조 · ${pg.players.length}/4명</b><div class="pendingTools">${canGame()?`<button class="miniBtn" ${i===0?'disabled':''} onclick="movePendingOrder('${pg.id}','up')">↑</button><button class="miniBtn" ${i===S.pendingGames.length-1?'disabled':''} onclick="movePendingOrder('${pg.id}','down')">↓</button>`:''}<span class="tag">${waited}분</span></div></div><div class="pendingGrid">${slots}</div><div class="pairSummary">${pairSummary(pg.players)}</div>${canGame()?`<div class="pendingActs"><button class="btn pri" ${pg.players.length!==4?'disabled':''} onclick="openCourtStart('${pg.id}')">코트 선택 · 경기 시작</button><button class="btn ghost" onclick="cancelPending('${pg.id}')">편성 취소</button></div>`:''}</div>`}
function renderQueue(){const q=sortedQueue();const selected=new Set(draft.filter(Boolean));$('queue').innerHTML=`<div class="title"><h2>게임대기</h2><span class="tag">${S.queue.length+S.pendingGames.reduce((n,g)=>n+g.players.length,0)}명</span></div>${canGame()?`<div class="composer"><div class="composerTitle">새 게임 편성</div><div class="slots">${draft.map((id,i)=>{const m=id?M(id):null;return `<div class="slot ${m?'filled':''}"><div class="slotLabel">${i<2?'A팀':'B팀'} ${i%2+1}</div>${m?`<button class="slotX" onclick="draftRemove(${i})">×</button><div class="slotName">${esc(m.name)} ${ageTag(m)} ${roleBadge(m)}</div><div class="meta">게임 ${dailyCount(id)}회 · ${waitMins(m)}분 대기</div>`:'<div class="meta">개인 게임대기에서 선택</div>'}</div>`}).join('')}</div><div class="pairSummary">${pairSummary(draft.filter(Boolean))}</div><div class="composerActs"><button class="btn ghost" onclick="clearDraft()">선택 비우기</button><button class="btn ghost" onclick="recommendDraft()">✨ 추천 구성</button><button class="btn pri" ${draft.filter(Boolean).length?'':'disabled'} onclick="registerDraft()">대기 등록</button></div></div>`:''}<div class="subhead"><b>편성대기 현황</b><span class="tag">${S.pendingGames.length}조</span></div>${S.pendingGames.length?S.pendingGames.map(pendingCard).join(''):'<div class="empty">편성대기 중인 조가 없습니다.</div>'}<div class="subhead"><b>개인 게임대기</b><span class="tag">${q.length}명</span></div><div class="note">게임횟수가 적은 순서 → 같은 횟수면 대기시간이 긴 순서입니다.</div>${q.length?q.map((id,i)=>{const m=M(id);if(!m)return'';return `<div class="card queueCard ${selected.has(id)?'selected':''}" ${canGame()?`onclick="draftClick('${id}')"`:''}><div class="ord">${i+1}</div><div><div class="name">${esc(m.name)} ${ageTag(m)} <span class="gamecnt">게임 ${dailyCount(id)}회</span> ${roleBadge(m)}</div><div class="meta">${esc(m.gender)} · ${waitMins(m)}분 대기</div></div><b>${selected.has(id)?'✓':''}</b></div>`}).join(''):'<div class="empty">개인 게임대기 회원이 없습니다.</div>'}`}
async function removePending(pid,id){if(!confirm(`${M(id)?.name||'회원'}님을 개인 게임대기로 내릴까요? 대기시간은 유지됩니다.`))return;try{await act('remove_from_pending',{pendingId:pid,memberId:id})}catch(e){showError(e)}}
async function movePendingOrder(pid,dir){try{await act('move_pending_order',{pendingId:pid,direction:dir})}catch(e){showError(e)}}
async function cancelPending(pid){if(!confirm('이 편성대기 조를 취소하고 전원을 개인 게임대기로 돌릴까요? 대기시간은 유지됩니다.'))return;try{await act('cancel_pending',{pendingId:pid})}catch(e){showError(e)}}
function openFillPending(pid){const pg=S.pendingGames.find(g=>g.id===pid);if(!pg||pg.players.length>=4)return;moveCtx={mode:'fill',targetPendingId:pid};const q=sortedQueue();const others=S.pendingGames.filter(g=>g.id!==pid&&g.players.length).flatMap(g=>g.players.map(id=>({g,id,m:M(id)}))).filter(x=>x.m);openModal(`<h3>빈자리 채우기 · ${pg.players.length}/4명</h3><div class="note">개인 게임대기 또는 다른 1~4인 편성대기 조에서 자유롭게 한 명을 이동할 수 있습니다.</div><div class="subhead"><b>개인 게임대기</b><span class="tag">${q.length}명</span></div>${q.map(id=>{const m=M(id);return `<button class="choiceBtn" onclick="fillFromQueue('${id}')"><b>${esc(m.name)} ${ageTag(m)} ${roleBadge(m)}</b><span class="meta">게임 ${dailyCount(id)}회 · ${waitMins(m)}분 대기</span></button>`}).join('')||'<div class="empty">없음</div>'}<div class="subhead"><b>다른 편성대기 조</b><span class="tag">${others.length}명</span></div>${others.map(x=>`<button class="choiceBtn" onclick="fillFromPending('${x.g.id}','${x.id}')"><b>${esc(x.m.name)} ${ageTag(x.m)} ${roleBadge(x.m)}</b><span class="meta">편성대기 ${S.pendingGames.indexOf(x.g)+1}조 · ${x.g.players.length}/4명</span></button>`).join('')||'<div class="empty">없음</div>'}<button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">취소</button>`)}
async function fillFromQueue(id,force=false){const target=moveCtx?.targetPendingId;if(!target)return;try{const x=await act('add_to_pending',{pendingId:target,memberId:id,forceRepeat:force},{repeat:{keep:()=>{moveCtx={mode:'fill',targetPendingId:target};fillFromQueue(id,true)},manual:()=>closeModal()}});if(x)closeModal()}catch(e){showError(e)}}
async function fillFromPending(source,id,force=false){const target=moveCtx?.targetPendingId;if(!target)return;try{const x=await act('move_pending_member',{sourcePendingId:source,targetPendingId:target,memberId:id,forceRepeat:force},{repeat:{keep:()=>{moveCtx={mode:'fill',targetPendingId:target};fillFromPending(source,id,true)},manual:()=>closeModal()}});if(x)closeModal()}catch(e){showError(e)}}
function openMoveMember(pid,id){const pg=S.pendingGames.find(g=>g.id===pid),m=M(id);if(!pg||!m)return;moveCtx={mode:'member',sourcePendingId:pid,memberId:id};const partial=S.pendingGames.filter(g=>g.id!==pid&&g.players.length<4),q=sortedQueue(),others=S.pendingGames.filter(g=>g.id!==pid);openModal(`<h3>${esc(m.name)} · 이동/교체</h3><div class="note">다른 미완성 조로 이동하거나 개인 게임대기/다른 대기조 회원과 맞교환할 수 있습니다. 대기시간은 유지됩니다.</div><div class="subhead"><b>빈자리 있는 대기조로 이동</b><span class="tag">${partial.length}조</span></div>${partial.map(g=>`<button class="choiceBtn" onclick="moveToPartial('${g.id}')"><b>편성대기 ${S.pendingGames.indexOf(g)+1}조 · ${g.players.length}/4명</b><span class="meta">${g.players.map(x=>M(x)?.name||'-').join(' · ')}</span></button>`).join('')||'<div class="empty">빈자리 조 없음</div>'}<div class="subhead"><b>개인 게임대기와 맞교환</b><span class="tag">${q.length}명</span></div>${q.map(qid=>{const qm=M(qid);return `<button class="choiceBtn" onclick="swapQueue('${qid}')"><b>${esc(qm.name)} ${ageTag(qm)}</b><span class="meta">${waitMins(qm)}분 대기</span></button>`}).join('')||'<div class="empty">없음</div>'}<div class="subhead"><b>다른 편성대기 조와 맞교환</b></div>${others.flatMap(g=>g.players.map(oid=>{const om=M(oid);return `<button class="choiceBtn" onclick="swapPending('${g.id}','${oid}')"><b>${esc(om?.name||'-')} ${om?ageTag(om):''}</b><span class="meta">편성대기 ${S.pendingGames.indexOf(g)+1}조</span></button>`})).join('')||'<div class="empty">없음</div>'}<button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">취소</button>`)}
async function moveToPartial(target,force=false){const c=moveCtx;if(!c)return;try{const x=await act('move_pending_member',{sourcePendingId:c.sourcePendingId,targetPendingId:target,memberId:c.memberId,forceRepeat:force},{repeat:{keep:()=>{moveCtx=c;moveToPartial(target,true)},manual:()=>closeModal()}});if(x)closeModal()}catch(e){showError(e)}}
async function swapQueue(qid,force=false){const c=moveCtx;if(!c)return;try{const x=await act('swap_pending_queue',{pendingId:c.sourcePendingId,fromMemberId:c.memberId,queueMemberId:qid,forceRepeat:force},{repeat:{keep:()=>{moveCtx=c;swapQueue(qid,true)},manual:()=>closeModal()}});if(x)closeModal()}catch(e){showError(e)}}
async function swapPending(targetPid,targetId,force=false){const c=moveCtx;if(!c)return;try{const x=await act('swap_pending_players',{fromPendingId:c.sourcePendingId,toPendingId:targetPid,fromMemberId:c.memberId,toMemberId:targetId,forceRepeat:force},{repeat:{keep:()=>{moveCtx=c;swapPending(targetPid,targetId,true)},manual:()=>closeModal()}});if(x)closeModal()}catch(e){showError(e)}}
function courtLabel(n){return String(S.courtNames?.[Number(n)-1]||`${n}코트`)}
function openCourtStart(pid){const pg=S.pendingGames.find(g=>g.id===pid);if(!pg||pg.players.length!==4)return;courtCtx={mode:'start',pendingId:pid};renderCourtPicker(null)}
function openCourtChange(gid){const g=S.games.find(x=>x.id===gid);if(!g)return;courtCtx={mode:'change',gameId:gid,current:g.court};renderCourtPicker(g.court)}
function renderCourtPicker(current){const used=new Set(S.games.filter(g=>courtCtx?.mode!=='change'||g.id!==courtCtx.gameId).map(g=>Number(g.court)));const avail=[];for(let n=1;n<=S.courtCount;n++)if(!used.has(n))avail.push(n);openModal(`<h3>${courtCtx?.mode==='start'?'경기 시작 코트 선택':'진행중 코트 변경'}</h3><div class="note">${courtCtx?.mode==='start'?'코트를 선택한 뒤 한 번 더 확인합니다.':'변경할 빈 코트를 선택해주세요.'}</div><div class="grid2">${avail.map(n=>`<button class="choiceBtn" onclick="chooseCourt(${n})"><b>${esc(courtLabel(n))}</b>${Number(current)===n?'<span class="meta">현재 코트</span>':''}</button>`).join('')}</div><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">취소</button>`)}
async function chooseCourt(n){const c=courtCtx;if(!c)return;if(c.mode==='start'){const pg=S.pendingGames.find(g=>g.id===c.pendingId),names=(pg?.players||[]).map(id=>M(id)?.name||'-').join(' · ');if(!confirm(`${courtLabel(n)}에 해당 편성대기 게임을 배정하고 경기를 시작하시겠습니까?\n${names}`))return;try{await act('begin_game',{pendingId:c.pendingId,court:n});closeModal();goView('queue')}catch(e){showError(e)}}else{if(!confirm(`${courtLabel(n)}로 코트를 변경하시겠습니까?`))return;try{await act('set_game_court',{gameId:c.gameId,court:n});closeModal()}catch(e){showError(e)}}}
async function renameCourt(n){if(!canGame())return;let name=prompt('새 코트 이름을 입력해주세요.',courtLabel(n));if(name===null)return;name=name.trim();if(/^\d+$/.test(name))name+='코트';if(!name)return;try{await act('set_court_name',{court:n,name})}catch(e){showError(e)}}
function playerLine(id){const m=M(id);return m?`<div class="p">${esc(m.name)} ${ageTag(m)} ${roleBadge(m)}<div class="meta">게임 ${dailyCount(id)}회</div></div>`:'-'}
function gameHtml(g){return `<div class="teams"><div class="team">${playerLine(g.players[0])}${playerLine(g.players[1])}</div><b>VS</b><div class="team">${playerLine(g.players[2])}${playerLine(g.players[3])}</div></div><div class="foot"><span class="meta">${new Date(g.startedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})} 시작</span><div class="gameBtns">${canGame()?`<button class="btn ghost" onclick="openCourtChange('${g.id}')">코트변경</button>`:''}<button class="btn danger" onclick="finishGameNow('${g.id}')">경기종료</button></div></div>`}
function renderPlaying(){let html='<div class="title"><h2>게임중</h2><span class="tag">30분 자동종료</span></div>';for(let n=1;n<=S.courtCount;n++){const g=S.games.find(x=>Number(x.court)===n);html+=`<div class="card courtCard"><div class="courtName">${canGame()?`<button onclick="renameCourt(${n})">${esc(courtLabel(n))}<br><small>✎</small></button>`:esc(courtLabel(n))}</div><div class="courtBody">${g?gameHtml(g):'<div class="empty">비어 있음</div>'}</div></div>`}$('playing').innerHTML=html}
async function finishGameNow(id){if(!confirm('정말 이 경기를 종료하시겠습니까?'))return;try{await act('finish_game',{gameId:id});goView('queue')}catch(e){showError(e)}}
function renderStats(){const mins=S.history.reduce((a,h)=>a+(Number(h.durationMin)||0),0),people=new Set(S.history.flatMap(h=>h.players||[])).size;$('stats').innerHTML=`<div class="title"><h2>오늘 통계</h2></div><div class="statsGrid"><div class="stat"><b>${S.history.length}</b>완료 게임</div><div class="stat"><b>${mins}분</b>플레이시간</div><div class="stat"><b>${people}</b>참여 인원</div></div><div class="card" style="margin-top:10px"><b>오늘 최근 경기</b>${S.history.length?S.history.slice().reverse().slice(0,20).map(h=>`<div class="historyRow"><b>${esc(h.courtName||courtLabel(h.court))}</b> ${(h.players||[]).map((id,i)=>esc(M(id)?.name||h.playerNames?.[i]||'삭제회원')).join(' · ')}<div class="meta">${h.durationMin||0}분${h.autoEnded?' · 자동종료':''}</div></div>`).join(''):'<div class="empty">완료된 게임이 없습니다.</div>'}</div>`}
function openPairs(id){const m=M(id);if(!m)return;const rows=S.members.filter(x=>x.id!==id).map(x=>({m:x,n:pairCount(id,x.id)})).sort((a,b)=>b.n-a.n||a.m.name.localeCompare(b.m.name,'ko'));openModal(`<h3>${esc(m.name)} · 같이한 경기</h3><div class="note">같은 4인 경기에 함께 들어간 횟수이며 같은 편/상대편은 구분하지 않습니다.</div>${rows.map(x=>`<div class="card between"><div><b>${esc(x.m.name)}</b><div class="meta">${esc(x.m.age)}${esc(x.m.cls)} · ${esc(x.m.gender)}</div></div><b>${x.n}회</b></div>`).join('')||'<div class="empty">비교할 회원이 없습니다.</div>'}<button class="btn ghost" style="width:100%" onclick="closeModal()">닫기</button>`)}
function renderSettings(){const mine=me.memberId?M(me.memberId):null;const tempEligible=S.members.filter(m=>m.type!=='guest'&&roleOf(m)==='member'&&m.state!=='out');$('settings').innerHTML=`<div class="title"><h2>설정</h2></div><div class="card"><div class="between"><div><b>현재 모임</b><div class="meta">${esc(group?.name||'-')}</div></div><span class="tag">${roleLabel(me.role)}</span></div></div>${mine?`<div class="card"><div class="between"><div><b>오늘 내 상태</b><div class="meta">${stateLabel(mine.state)}</div></div><div class="memberBtns"><button class="btn enter" onclick="setMySetting('waiting')">운동</button><button class="btn watch" onclick="setMySetting('spectator')">관람</button><button class="btn danger" onclick="setMySetting('out')">퇴장</button></div></div></div>`:'<div class="note">현재 모임 회원명부에 본인 이름이 없어 참가상태 변경은 표시되지 않습니다.</div>'}${(me.globalAdmin||me.role==='manager'||me.role==='organizer')?`<div class="card"><b>당일 임시편성자</b><div class="meta" style="margin:5px 0 10px">오늘 참석한 일반회원에게 당일 게임편성 권한만 부여합니다.</div>${tempEligible.map(m=>`<div class="between" style="padding:7px 0;border-bottom:1px solid #edf0f7"><span>${esc(m.name)} ${ageTag(m)}</span><button class="btn ${isTemp(m)?'danger':'ghost'}" onclick="toggleTemp('${m.id}',${!isTemp(m)})">${isTemp(m)?'해제':'임시 지정'}</button></div>`).join('')||'<div class="empty">지정 가능한 참석 회원이 없습니다.</div>'}</div>`:''}${canGame()?`<div class="card"><b>코트 설정</b><div class="field" style="margin-top:9px"><label>사용 코트 수 (1~16)</label><input id="courtCountInput" type="number" min="1" max="16" inputmode="numeric" value="${S.courtCount}"></div><button class="btn pri" onclick="saveCourtCount()">코트 수 저장</button></div>`:''}${canReset()?`<div class="card"><b>모임 당일 운영 리셋</b><div class="warn">이 모임의 오늘 경기·대기·입장상태를 초기화하고 이 모임에 로그인한 이용자를 로그아웃합니다. 누적 게임횟수와 같이한 경기 기록은 유지합니다.</div><button class="btn danger" style="width:100%" onclick="resetDaily()">당일 운영 리셋</button></div>`:''}<div class="card"><div class="between"><div><b>프로그램 버전</b><div class="meta">콕매치 v35 · 다중 모임 운영</div></div><span class="tag">운영본</span></div><button id="forceUpdateBtn" class="btn pri" style="width:100%;margin-top:10px" onclick="forceUpdateApp()">↻ 최신 버전으로 새로고침</button>${me.globalAdmin?'<a class="btn ghost" style="display:block;text-align:center;text-decoration:none;margin-top:7px" href="/versions/">구버전 보기</a>':''}<div class="meta" style="margin-top:8px">${me.globalAdmin?'총관리자 최신화 시 본인을 제외한 모든 로그인 세션을 종료합니다.':''} 현재 화면과 스크롤 위치는 유지합니다.</div></div><div class="card"><b>홈 화면에 추가</b><div class="meta" style="margin-top:6px;line-height:1.7">아이폰 Safari: 공유 → 홈 화면에 추가<br>갤럭시 Chrome: 메뉴 → 홈 화면에 추가</div></div>`}
async function setMySetting(mode){try{await act('set_my_attendance',{mode})}catch(e){showError(e)}}
async function toggleTemp(id,enabled){try{await act('set_temp',{memberId:id,enabled})}catch(e){showError(e)}}
async function saveCourtCount(){const n=Number($('courtCountInput').value);try{await act('set_courts',{count:n});alert(`코트 수를 ${n}개로 설정했습니다.`)}catch(e){showError(e)}}
async function resetDaily(){const pin=prompt(`${me.globalAdmin?'총관리자':'모임관리자'} PIN을 입력해주세요.`);if(pin===null)return;if(!confirm(`${group.name}의 당일 운영기록을 초기화하시겠습니까?`))return;try{await act('reset_daily',{pin});if(!me.globalAdmin){await reloginLatest()}else{await loadState();goView('settings')}}catch(e){showError(e)}}
async function openGroupSwitch(){if(!me?.globalAdmin)return;openModal(`<h3>운영 모임 선택</h3><div class="choiceList">${groups.map(g=>`<button class="choiceBtn" onclick="switchGroup('${g.groupId}')"><b>${esc(g.name)}</b></button>`).join('')}</div><button class="btn ghost" style="width:100%;margin-top:9px" onclick="closeModal()">취소</button>`)}
async function switchGroup(id,view='members'){currentGroupId=id;localStorage.setItem(GROUP_KEY,id);closeModal();try{await loadState();goView(view)}catch(e){showError(e)}}
async function loadGroups(){if(!canManageGroups())return;const x=await request('groups','POST',{action:'list_groups'});groupSummaries=x.groups||[];renderGroups()}
function renderGroups(){if(!$('groups')||!canManageGroups())return;$('groups').innerHTML=`<div class="title"><h2>모임관리</h2><button class="btn pri" onclick="openGroupEditor()">+ 모임 생성</button></div><div class="note">총관리자는 모든 모임을 생성·수정·삭제하고 각 모임 회원명부에서 모임관리자와 게임편성자를 지정할 수 있습니다. 일반회원 로그인에는 각 모임의 PIN이 사용됩니다.</div>${groupSummaries.map(g=>`<div class="card groupCard ${g.isActive?'':'inactive'}"><div class="between"><div><b>${esc(g.name)}</b><div class="meta">${g.isActive?'운영중':'삭제됨(복구 가능)'}</div></div><span class="tag">${g.memberCount}명</span></div><div class="groupStats"><span>모임관리자 ${g.managers.length?esc(g.managers.join(', ')):'미지정'}</span><span>게임편성자 ${g.organizers.length?esc(g.organizers.join(', ')):'없음'}</span><span>대기 ${g.waiting}</span><span>게임중 ${g.playing}</span></div><div class="groupActs">${g.isActive?`<button class="btn pri" onclick="switchGroup('${g.groupId}','members')">인원/권한 관리</button><button class="btn ghost" onclick="openGroupEditor('${g.groupId}')">모임 수정</button><button class="btn danger" onclick="deleteGroup('${g.groupId}')">모임 삭제</button>`:`<button class="btn pri" onclick="restoreGroup('${g.groupId}')">모임 복구</button>`}</div></div>`).join('')||'<div class="empty">등록된 모임이 없습니다.</div>'}`}
function openGroupEditor(id=''){const g=id?groupSummaries.find(x=>x.groupId===id):null;openModal(`<h3>${g?'모임 수정':'새 모임 생성'}</h3><div class="field"><label>모임 이름</label><input id="fgName" value="${esc(g?.name||'')}"></div><div class="field"><label>${g?'새 모임 PIN (변경할 때만 입력)':'모임 PIN (숫자 4~8자리)'}</label><input id="fgPin" type="password" inputmode="numeric" placeholder="${g?'비우면 기존 PIN 유지':'일반회원 로그인용 PIN'}"></div><div class="acts"><button class="btn ghost" onclick="closeModal()">취소</button><button class="btn pri" onclick="saveGroup('${id}')">저장</button></div>`)}
async function saveGroup(id){const name=$('fgName').value.trim(),pin=$('fgPin').value.trim();if(!name)return alert('모임 이름을 입력해주세요.');try{await request('groups','POST',{action:id?'update_group':'create_group',groupId:id,name,pin});closeModal();await loadGroups();if(!id)alert('모임을 생성했습니다. 일반회원에게 해당 모임 PIN을 안내해주세요.')}catch(e){showError(e)}}
async function deleteGroup(id){const g=groupSummaries.find(x=>x.groupId===id);if(!g||!confirm(`${g.name} 모임을 삭제하시겠습니까?\n데이터는 복구를 위해 보존되며 운영목록에서 숨겨집니다.`))return;try{await request('groups','POST',{action:'delete_group',groupId:id});await loadGroups()}catch(e){showError(e)}}
async function restoreGroup(id){try{await request('groups','POST',{action:'restore_group',groupId:id});await loadGroups()}catch(e){showError(e)}}
function saveRefreshState(){try{sessionStorage.setItem(REFRESH_KEY,JSON.stringify({view:currentView,y:Math.max(0,scrollY||0),groupId:currentGroupId,at:Date.now()}));if('scrollRestoration'in history)history.scrollRestoration='manual'}catch{}}
function restoreRefreshState(){let x=null;try{x=JSON.parse(sessionStorage.getItem(REFRESH_KEY)||'null')}catch{}if(!x||Date.now()-Number(x.at||0)>120000)return;sessionStorage.removeItem(REFRESH_KEY);if(x.groupId&&me?.globalAdmin&&x.groupId!==currentGroupId){currentGroupId=x.groupId;localStorage.setItem(GROUP_KEY,x.groupId);loadState().then(()=>{goView(x.view||'settings');setTimeout(()=>scrollTo(0,Number(x.y)||0),100)}).catch(()=>{});return}goView(x.view||'settings');requestAnimationFrame(()=>requestAnimationFrame(()=>scrollTo(0,Number(x.y)||0)));setTimeout(()=>scrollTo(0,Number(x.y)||0),250)}
async function forceUpdateApp(){saveRefreshState();const b=$('forceUpdateBtn');if(b){b.disabled=true;b.textContent=me?.globalAdmin?'전체 이용자 최신화 중...':'최신 버전 확인 중...'}try{if(me?.globalAdmin){const r=await fetch(ADMIN_REFRESH_API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+T},body:'{}',cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'전체 이용자 최신화에 실패했습니다.')}if('caches'in window){const ks=await caches.keys();await Promise.all(ks.map(k=>caches.delete(k)))}if('serviceWorker'in navigator){const rs=await navigator.serviceWorker.getRegistrations();await Promise.all(rs.map(r=>r.unregister().catch(()=>{})))}await fetch('/index.html?refresh='+Date.now(),{cache:'no-store'}).catch(()=>null);location.replace('/?refresh='+Date.now())}catch(e){if(b){b.disabled=false;b.textContent='↻ 최신 버전으로 새로고침'}showError(e)}}
async function boot(){renderShell();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});if(!T){$('login').classList.remove('hide');return}try{await loadState();$('login').classList.add('hide')}catch(e){if(!reloginBusy){localStorage.removeItem(TOKEN_KEY);T='';$('login').classList.remove('hide');renderLoginName()}}}
document.addEventListener('click',e=>{if(e.target?.id==='modal')closeModal()});setInterval(()=>{if(T&&!reloginBusy)loadState().catch(()=>{})},3000);setInterval(()=>{if(me)renderAll()},60000);boot();