(()=>{
const POLL21_API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-v21-api';
const DEV21='박태영';
let selectedDate21=today21(),month21=selectedDate21.slice(0,7),busy21=new Set();

function today21(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function polls21(){S.attendancePolls=Array.isArray(S?.attendancePolls)?S.attendancePolls:[];return S.attendancePolls}
function poll21(id){return polls21().find(p=>String(p.id)===String(id))}
function votes21(p){p.memberVotes=p?.memberVotes&&typeof p.memberVotes==='object'?p.memberVotes:{};return p.memberVotes}
function guests21(p){p.guestEntries=Array.isArray(p?.guestEntries)?p.guestEntries:[];return p.guestEntries}
function mine21(){if(me?.memberId){const m=M(String(me.memberId));if(m)return m}const n=String(me?.displayName||'').trim();return (S.members||[]).find(m=>String(m?.name||'').trim()===n)||null}
function staff21(){const m=mine21();return !!me&&(me.globalAdmin||me.role==='manager'||me.role==='organizer'||me.tempOrganizer||(m&&typeof isTemp==='function'&&isTemp(m)))}
function canVote21(){const m=mine21();return !!m&&m.type!=='guest'}
function endMs21(p){const d=String(p?.date||''),t=String(p?.endTime||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||!/^\d{2}:(00|30)$/.test(t))return 0;return Date.parse(`${d}T${t}:00+09:00`)}
function active21(){return polls21().filter(p=>{const e=endMs21(p);return !e||e>Date.now()}).slice().sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.time||'').localeCompare(String(b.time||'')))}
function yesMembers21(p){const v=votes21(p);return Object.keys(v).filter(id=>v[id]==='yes').map(id=>M(id)).filter(m=>m&&m.type!=='guest')}
function count21(p){const member=yesMembers21(p).length,guest=guests21(p).length;return {member,guest,total:member+guest}}
function totalLimit21(p){return Math.max(0,Math.floor(Number(p?.totalLimit)||0))}
function guestLimit21(p){return Math.max(0,Math.floor(Number(p?.guestLimit)||0))}
function hiddenAdmin21(){return String(S?.adminBadgeVisibility||'all')==='hidden'}
function viewerDev21(){return !!me&&String(me.displayName||'').trim()===DEV21&&me.globalAdmin===true}
function roleRank21(m){const self=(me?.memberId&&String(m?.id)===String(me.memberId))||(!me?.memberId&&String(m?.name||'').trim()===String(me?.displayName||'').trim());if(self)return -100;const r=roleOf(m);if(r==='admin')return hiddenAdmin21()&&!viewerDev21()?4:0;if(r==='manager')return 1;if(r==='organizer')return 2;if(typeof isTemp==='function'&&isTemp(m))return 3;return 4}
function role21(m){return m?.type==='guest'?'<span class="roleBadge guest45">게스트</span>':roleBadge(m)}
function gender21(m){const f=m?.gender==='여',label=f?'여성':'남성';return `<span class="pollGenderPerson19 ${f?'female':'male'}" title="${label}" aria-label="${label}"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"></circle><path d="M4.5 21c.5-5 3.2-8 7.5-8s7 3 7.5 8z"></path></svg></span>`}
function grade21(m){return `<span class="tag">${esc(String(m?.age||'30'))}${esc(String(m?.cls||'C'))}</span>`}
function ymShift21(ym,delta){const [y,m]=String(ym).split('-').map(Number),d=new Date(Date.UTC(y,m-1+delta,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`}
function date21(y,m,d){return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}

async function request21(action,body={}){const r=await fetch(POLL21_API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+T},body:JSON.stringify({action,groupId:currentGroupId,...body}),cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'처리에 실패했습니다.');if(x.data){S=x.data;normalizeClient()}return x}

function calendar21(){
 const today=today21(),cur=today.slice(0,7),[y,m]=month21.split('-').map(Number),first=new Date(Date.UTC(y,m-1,1)).getUTCDay(),last=new Date(Date.UTC(y,m,0)).getUTCDate(),has=new Set(active21().map(p=>String(p.date||''))),cells=[];
 for(let i=0;i<first;i++)cells.push('<span class="pollCalBlank21"></span>');
 for(let d=1;d<=last;d++){const dt=date21(y,m,d),past=dt<today,withPoll=has.has(dt),sel=dt===selectedDate21,isToday=dt===today;cells.push(`<button class="pollCalDay21 ${withPoll?'hasPoll':''} ${sel?'selected':''} ${isToday?'today':''}" ${past?'disabled':''} onclick="selectPollDate21('${dt}')"><span>${d}</span></button>`)}
 return `<div class="pollCalendar21"><div class="pollCalHead21"><button class="pollCalNav21" ${month21<=cur?'disabled':''} onclick="movePollMonth21(-1)">‹</button><b>${y}년 ${m}월</b><button class="pollCalNav21" onclick="movePollMonth21(1)">›</button></div><div class="pollCalWeek21"><span>일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span>토</span></div><div class="pollCalGrid21">${cells.join('')}</div><div class="pollCalLegend21"><span><i></i> 투표 있음</span><span>선택 ${selectedDate21.slice(5).replace('-','/')}</span></div></div>`;
}
window.selectPollDate21=function(dt){if(String(dt)<today21())return;selectedDate21=String(dt);month21=selectedDate21.slice(0,7);replacePoll21()};
window.movePollMonth21=function(delta){const next=ymShift21(month21,Number(delta)||0),cur=today21().slice(0,7);if(next<cur)return;month21=next;selectedDate21=next===cur?today21():`${next}-01`;replacePoll21()};

function countBoxes21(p){const c=count21(p),tl=totalLimit21(p),gl=guestLimit21(p);return `<div class="pollCounts21"><div class="pollCountBox21 total"><b>${tl?`${c.total}/${tl}`:c.total}</b><span>전체</span><small>${tl?'정원':'참석'}</small></div><div class="pollCountBox21 member"><b>${c.member}</b><span>회원</span><small>참석</small></div><div class="pollCountBox21 guest"><b>${gl?`${c.guest}/${gl}`:c.guest}</b><span>게스트</span><small>${gl?'정원':'참석'}</small></div></div>`}
function pollCard21(p){const c=count21(p),m=mine21(),on=!!m&&votes21(p)[String(m.id)]==='yes',staff=staff21(),closed=!!p.guestClosed;return `<div class="card pollCard21"><div class="pollTitleRow21"><div class="pollTitle21">${esc(p.title||'운동 참석 투표')}</div>${staff?`<div class="pollHeadBtns19"><button class="miniBtn" onclick="openPollEdit90('${esc(p.id)}')">수정</button><button class="miniBtn" onclick="deletePoll72('${esc(p.id)}')">삭제</button></div>`:''}</div>${countBoxes21(p)}<div class="pollActions21">${canVote21()?`<button class="btn ${on?'pollAttendOn21':'pri'}" onclick="togglePollVote21('${esc(p.id)}',this)">${on?'✓ 참석중 · 다시 누르면 취소':'참석'}</button>`:'<button class="btn ghost" disabled>회원만 참석</button>'}<button class="btn ghost" onclick="openPollAttendees21('${esc(p.id)}')">참석 명단 ${c.total}명</button></div>${staff?`<div class="pollGuestAdmin21">${closed?`<button class="btn ghost pollGuestClosed19" disabled>게스트 마감</button><button class="miniBtn" onclick="toggleGuestClosed19('${esc(p.id)}',false)">모집 재개</button>`:`<button class="btn ghost" onclick="openGuestAdd72('${esc(p.id)}')">+ 게스트 참가 추가</button><button class="miniBtn" onclick="toggleGuestClosed19('${esc(p.id)}',true)">게스트 모집 마감</button>`}</div>`:''}</div>`}
function section21(){const ps=active21().filter(p=>String(p.date||'')===selectedDate21);return `${calendar21()}<div class="subhead pollHead90"><b>운동 참석 투표</b>${staff21()?'<button class="btn pri" onclick="openPollCreate72()">+ 투표 만들기</button>':''}</div>${ps.length?ps.map(pollCard21).join(''):`<div class="empty pollEmpty90">${selectedDate21.slice(5).replace('-','/')} 예정된 참석 투표가 없습니다.</div>`}`}
function replacePoll21(){const box=$('stats');if(!box)return;let wrap=box.querySelector('.pollWrap90');if(!wrap){wrap=document.createElement('div');wrap.className='pollWrap90';const recent=[...box.querySelectorAll(':scope > .card')].find(c=>(c.textContent||'').includes('오늘 최근 경기'));if(recent)recent.insertAdjacentElement('beforebegin',wrap);else box.appendChild(wrap)}wrap.innerHTML=section21()}

window.togglePollVote21=async function(pid,btn){const key='v:'+pid;if(busy21.has(key))return;const p=poll21(pid),m=mine21();if(!p||!m||m.type==='guest')return;const mid=String(m.id),old={...votes21(p)},was=old[mid]==='yes';if(was)delete p.memberVotes[mid];else{const c=count21(p),l=totalLimit21(p);if(l>0&&c.total>=l)return alert(`참석 인원 ${l}명이 모두 찼습니다.`);p.memberVotes[mid]='yes'}busy21.add(key);if(btn)btn.disabled=true;replacePoll21();try{await request21('poll_toggle_vote',{pollId:pid});replacePoll21()}catch(e){p.memberVotes=old;showError(e);replacePoll21()}finally{busy21.delete(key)}};
window.votePoll72=window.togglePollVote21;

function attendeeHtml21(id){const p=poll21(id);if(!p)return'';const order=new Map((S.members||[]).map((m,i)=>[String(m.id),i])),members=yesMembers21(p).sort((a,b)=>roleRank21(a)-roleRank21(b)||(order.get(String(a.id))??99999)-(order.get(String(b.id))??99999)),gs=guests21(p).slice(),staff=staff21(),c=count21(p);const mr=members.map(m=>`<div class="pollAttendeeCard21 attendeeRow" data-kind="member" data-id="${esc(m.id)}"><div class="pollAttendeeMain21">${gender21(m)}<span class="pollAttendeeName21">${esc(m.name)}</span>${grade21(m)}${role21(m)}</div>${staff?`<button class="pollRemove21" onclick="removePollMember21('${esc(id)}','${esc(m.id)}',this)">×</button>`:''}</div>`).join('');const gr=gs.map(g=>`<div class="pollAttendeeCard21 attendeeRow" data-kind="guest" data-id="${esc(g.id)}"><div><div class="pollAttendeeMain21">${gender21(g)}<span class="pollAttendeeName21">${esc(g.name)}</span>${grade21(g)}${role21({type:'guest'})}</div><div class="pollGuestMeta21">${esc(g.year||'')}년생${g.inviter?` · 초대 ${esc(g.inviter)}`:''}</div></div>${staff?`<button class="pollRemove21" onclick="removePollGuest21('${esc(id)}','${esc(g.id)}',this)">×</button>`:''}</div>`).join('');return `<h3>참석 명단 · 총 ${c.total}명</h3>${countBoxes21(p)}<div class="pollAttendeeSection21"><div class="pollAttendeeHead21"><b>회원</b><span class="tag">${members.length}명</span></div><div id="pollMemberRows21">${mr||'<div class="empty">참석 회원이 없습니다.</div>'}</div></div><div class="pollAttendeeSection21"><div class="pollAttendeeHead21"><b>게스트</b><span class="tag">${gs.length}명</span></div><div id="pollGuestRows21">${gr||'<div class="empty">등록된 게스트가 없습니다.</div>'}</div></div><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">닫기</button>`}
function copyGradeLook21(){const root=$('modalSheet');if(!root)return;const refs={};document.querySelectorAll('#members .memberCard').forEach(card=>{const tag=card.querySelector('.tag'),txt=String(tag?.textContent||'').trim().toUpperCase(),g=(txt.match(/([A-E])$/)||[])[1];if(!tag||!g||refs[g])return;const ts=getComputedStyle(tag),cs=getComputedStyle(card);refs[g]={bg:ts.backgroundColor,color:ts.color,border:ts.borderColor,card:cs.backgroundColor}});root.querySelectorAll('.pollAttendeeCard21').forEach(row=>{const tag=row.querySelector('.tag'),g=(String(tag?.textContent||'').trim().toUpperCase().match(/([A-E])$/)||[])[1];const r=refs[g];if(!tag||!r)return;tag.style.setProperty('background',r.bg,'important');tag.style.setProperty('color',r.color,'important');tag.style.setProperty('border-color',r.border,'important');row.style.setProperty('background-color',r.card,'important');row.style.setProperty('border-radius','12px','important')})}
window.openPollAttendees21=function(id){const html=attendeeHtml21(id);if(!html)return;openModal(html);requestAnimationFrame(copyGradeLook21)};
window.openPollAttendees18=window.openPollAttendees21;window.openPollMembers72=window.openPollAttendees21;window.openPollGuests72=window.openPollAttendees21;

function immediateRemove21(btn,kind){const row=btn?.closest('.pollAttendeeCard21');if(row)row.remove();const host=$(kind==='member'?'pollMemberRows21':'pollGuestRows21');if(host&&!host.querySelector('.pollAttendeeCard21'))host.innerHTML=`<div class="empty">${kind==='member'?'참석 회원이 없습니다.':'등록된 게스트가 없습니다.'}</div>`}
window.removePollMember21=async function(pid,mid,btn){if(!staff21())return;if(!confirm('이 회원을 참석명단에서 제외하시겠습니까?'))return;const key=`m:${pid}:${mid}`;if(busy21.has(key))return;const p=poll21(pid);if(!p)return;const old={...votes21(p)};delete p.memberVotes[String(mid)];busy21.add(key);if(btn)btn.disabled=true;immediateRemove21(btn,'member');try{openModal(attendeeHtml21(pid));requestAnimationFrame(copyGradeLook21);await request21('poll_member_remove',{pollId:pid,memberId:mid});replacePoll21()}catch(e){p.memberVotes=old;showError(e);openPollAttendees21(pid)}finally{busy21.delete(key)}};
window.removePollGuest21=async function(pid,gid,btn){if(!staff21())return;if(!confirm('이 게스트를 참석명단에서 삭제하시겠습니까?'))return;const key=`g:${pid}:${gid}`;if(busy21.has(key))return;const p=poll21(pid);if(!p)return;const old=guests21(p).slice();p.guestEntries=old.filter(g=>String(g.id)!==String(gid));busy21.add(key);if(btn)btn.disabled=true;immediateRemove21(btn,'guest');try{openModal(attendeeHtml21(pid));requestAnimationFrame(copyGradeLook21);await request21('poll_guest_remove',{pollId:pid,guestId:gid});replacePoll21()}catch(e){p.guestEntries=old;showError(e);openPollAttendees21(pid)}finally{busy21.delete(key)}};
window.removePollMember19=function(pid,mid){const row=$('modalSheet')?.querySelector(`.pollAttendeeCard21[data-kind="member"][data-id="${CSS.escape(String(mid))}"]`);return removePollMember21(pid,mid,row?.querySelector('.pollRemove21'))};
window.removePollGuest72=function(pid,gid){const row=$('modalSheet')?.querySelector(`.pollAttendeeCard21[data-kind="guest"][data-id="${CSS.escape(String(gid))}"]`);return removePollGuest21(pid,gid,row?.querySelector('.pollRemove21'))};

const openCreatePrev21=window.openPollCreate72;window.openPollCreate72=function(){openCreatePrev21();setTimeout(()=>{const d=$('pollDate19');if(d){d.min=today21();d.value=selectedDate21;d.dispatchEvent(new Event('change',{bubbles:true}))}},0)};
const openEditPrev21=window.openPollEdit90;window.openPollEdit90=function(id){openEditPrev21(id);setTimeout(()=>{const d=$('pollDate19');if(d)d.min=today21()},0)};

const renderStatsPrev21=renderStats;renderStats=function(){renderStatsPrev21();replacePoll21()};
const renderSettingsPrev21=renderSettings;renderSettings=function(){renderSettingsPrev21();const b=$('settings');if(!b)return;[...b.querySelectorAll('.meta')].forEach(el=>{if(/콕매치 v(?:\d+|\d+\.\d+)/.test(el.textContent||''))el.textContent='콕매치 v2.1 · 월간달력 정상화 · 참석토글 · 참석명단 복구 · 인원가독성 개선'})};
if(me&&currentView==='stats')renderStats();
})();
