(()=>{
const V60_API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-v60-api';
function actor60(){return me?.globalAdmin?'admin':me?.tempOrganizer?'temp':String(me?.role||'member')}
function canAttendance60(){return ['admin','manager','organizer','temp'].includes(actor60())}
function canMemberInfo60(){return ['admin','manager','organizer'].includes(actor60())}
function canTempAssign60(){return ['admin','manager','organizer'].includes(actor60())}
function canFinish60(){const mine=me?.memberId?M(me.memberId):null;return !!me&&(me.globalAdmin||!!mine&&mine.type!=='guest')}
function editable60(m){return canMemberInfo60()&&(roleOf(m)!=='admin'||!!me?.globalAdmin)}
function deletable60(m){return canMemberInfo60()&&roleOf(m)!=='admin'}
function roleOptions60(){return me?.globalAdmin||me?.role==='manager'?['member','organizer','manager']:[]}
async function v60Request(op,body={}){const r=await fetch(V60_API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+T},body:JSON.stringify({op,groupId:currentGroupId,...body}),cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401){reloginLatest();throw new Error('로그인이 만료되었습니다.')}throw new Error(x.error||'v60 작업에 실패했습니다.')}return x}
memberControls=function(m){const attendance=canAttendance60(),edit=editable60(m);let bs='';if(attendance&&m.state!=='playing'&&m.state!=='matched'){if(m.state!=='waiting')bs+=`<button class="btn enter" onclick="setOther('${m.id}','waiting')">입장</button>`;if(m.state!=='spectator')bs+=`<button class="btn watch" onclick="setOther('${m.id}','spectator')">관람</button>`;if(m.state!=='out')bs+=`<button class="btn danger" onclick="setOther('${m.id}','out')">퇴장</button>`}if(edit)bs+=`<button class="btn ghost" onclick="openEditMember('${m.id}')">수정</button>`;return `<div class="memberActions60"><div class="status">${stateLabel(m.state)}</div><div class="memberBtns">${bs}</div></div>`};
const renderMembers59=renderMembers;renderMembers=function(){renderMembers59();const box=$('members');if(!box)return;const note=box.querySelector('.note');if(note){const a=actor60();note.textContent=a==='admin'?'총관리자는 모든 모임과 회원정보·역할·운영을 관리할 수 있습니다.':a==='manager'?'모임관리자는 현재 모임의 모든 회원정보·역할·입장상태·운영을 관리할 수 있습니다.':a==='organizer'?'게임편성자는 현재 모임의 회원정보 관리, 일반회원·게스트 관리, 임시편성자 지정과 게임운영을 할 수 있습니다.':a==='temp'?'임시편성자는 회원정보 수정 없이 입장상태와 게임편성·코트운영만 할 수 있습니다.':'회원정보와 현재 참가상태를 확인할 수 있습니다.'}};
openEditMember=function(id){const m=M(id);if(!m)return;if(!editable60(m))return alert('이 회원정보를 수정할 권한이 없습니다.');editMemberId=id;openMemberModal(m)};openAddMember=function(){if(!canMemberInfo60())return alert('회원등록 권한이 없습니다.');editMemberId=null;openMemberModal(null)};
openMemberModal=function(m){const add=!m,r=roleOf(m),opts=roleOptions60(),isAdmin=!add&&r==='admin',organizer=me?.role==='organizer'&&!me?.globalAdmin;const roleSelect=opts.length?`<div class="field"><label>역할</label><select id="fmRole" onchange="syncMember60()">${opts.map(x=>`<option value="${x}" ${(add?(x==='member'):r===x)?'selected':''}>${roleLabel(x)}</option>`).join('')}</select></div><div id="fmPinWrap" class="field ${r==='member'||add?'hide':''}"><label>${add?'역할 PIN':'새 역할 PIN (변경할 때만 입력)'}</label><input id="fmPin" type="tel" inputmode="numeric" maxlength="8" autocomplete="off" placeholder="숫자 4~8자리"></div>`:'';const typeLocked=organizer&&!add&&r!=='member';openModal(`<h3>${add?'회원등록':'회원 정보 수정'}</h3><div class="note">${organizer?'게임편성자는 회원 기본정보와 일반회원·게스트 구분을 관리할 수 있으며 관리자 역할은 변경할 수 없습니다.':'회원 기본정보·구분·역할을 관리합니다.'}</div><div class="field"><label>이름</label><input id="fmName" value="${esc(m?.name||'')}" ${isAdmin?'disabled':''}></div><div class="grid2"><div class="field"><label>출생연도</label><input id="fmYear" type="number" inputmode="numeric" value="${esc(m?.year||'')}"></div><div class="field"><label>성별</label><select id="fmGender"><option ${m?.gender!=='여'?'selected':''}>남</option><option ${m?.gender==='여'?'selected':''}>여</option></select></div><div class="field"><label>급수</label><select id="fmCls">${['A','B','C','D','E'].map(c=>`<option ${String(m?.cls||'C')===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>구분</label><select id="fmType" onchange="syncMember60()" ${isAdmin||typeLocked?'disabled':''}><option value="member" ${m?.type!=='guest'?'selected':''}>일반회원</option><option value="guest" ${m?.type==='guest'?'selected':''}>게스트</option></select></div></div>${roleSelect}<div id="fmInviterWrap60" class="field ${m?.type==='guest'?'':'hide'}"><label>초대인</label><input id="fmInviter60" value="${esc(m?.inviter||'')}" maxlength="40" placeholder="초대한 회원 이름"></div><div class="acts">${!add&&deletable60(m)?'<button class="btn danger" onclick="deleteMemberNow()">삭제</button>':''}<button class="btn ghost" onclick="closeModal()">취소</button><button class="btn pri" onclick="saveMemberNow()">${add?'등록':'저장'}</button></div>`);setTimeout(()=>syncMember60(),0)};
window.syncMember60=function(){const type=$('fmType')?.value||'member',role=$('fmRole');if(role&&type==='guest')role.value='member';if(role)role.disabled=type==='guest';const rr=role?.value||'member';$('fmPinWrap')?.classList.toggle('hide',rr==='member'||type==='guest');$('fmInviterWrap60')?.classList.toggle('hide',type!=='guest')};
saveMemberNow=async function(){const cur=editMemberId?M(editMemberId):null,organizer=me?.role==='organizer'&&!me?.globalAdmin;if(!canMemberInfo60())return alert('회원정보 관리 권한이 없습니다.');const type=$('fmType')?.value||(cur?.type||'member');const role=organizer?(cur?roleOf(cur):'member'):($('fmRole')?.value||(cur?roleOf(cur):'member'));const body={memberId:editMemberId||'',name:$('fmName')?.value.trim()||(cur?.name||''),year:Number($('fmYear')?.value),gender:$('fmGender')?.value||'남',cls:$('fmCls')?.value||'C',type,role,pin:$('fmPin')?.value.trim()||'',inviter:type==='guest'?($('fmInviter60')?.value.trim()||''):''};if(!body.name)return alert('이름을 입력해주세요.');if(type==='guest'&&!body.inviter)return alert('게스트의 초대인을 입력해주세요.');try{const x=await v60Request('member_save',body);S=x.data;normalizeClient();closeModal();renderAll()}catch(e){showError(e)}};
deleteMemberNow=async function(){const m=M(editMemberId);if(!m||!deletable60(m))return alert('이 회원을 삭제할 권한이 없습니다.');if(!confirm(`${m.name} 회원정보를 삭제하시겠습니까?`))return;try{const x=await v60Request('member_delete',{memberId:m.id});S=x.data;normalizeClient();closeModal();renderAll()}catch(e){showError(e)}};
const act59=act;act=async function(action,body={},opts={}){const routed=['set_temp','set_my_attendance','set_member_attendance','create_pending','remove_from_pending','add_to_pending','move_pending_order','cancel_pending','begin_game','finish_game','set_game_court','set_courts','set_court_name'];if(!routed.includes(action))return act59(action,body,opts);const x=await v60Request('action',{action,...body});if(x.data){S=x.data;normalizeClient();renderAll()}return x};
gameHtml=function(g){return `<div class="teams"><div class="team">${playerLine(g.players[0])}${playerLine(g.players[1])}</div><b>VS</b><div class="team">${playerLine(g.players[2])}${playerLine(g.players[3])}</div></div><div class="foot"><span class="meta">${new Date(g.startedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})} 시작</span><div class="gameBtns">${canGame()?`<button class="btn ghost" onclick="openCourtChange('${g.id}')">코트변경</button>`:''}${canFinish60()?`<button class="btn danger" onclick="finishGameNow('${g.id}')">경기종료</button>`:''}</div></div>`};
const renderSettings59=renderSettings;renderSettings=function(){renderSettings59();const box=$('settings');if(!box)return;[...box.querySelectorAll(':scope > .card')].forEach(c=>{const t=c.textContent||'';if(t.includes('당일 임시편성자')||t.includes('다. 회원정보 전체 정리 초기화'))c.remove()});if(canTempAssign60()){const eligible=S.members.filter(m=>m.type!=='guest'&&roleOf(m)==='member'&&m.state!=='out'),versionCard=[...box.querySelectorAll(':scope > .card')].find(c=>(c.textContent||'').includes('프로그램 버전')),html=`<div class="card"><b>당일 임시편성자</b><div class="meta" style="margin:5px 0 10px">일반회원에게 오늘만 게임편성·입장상태·코트설정 권한을 부여합니다.</div>${eligible.map(m=>`<div class="between" style="padding:7px 0;border-bottom:1px solid #edf0f7"><span>${esc(m.name)} ${ageTag(m)}</span><button class="btn ${isTemp(m)?'danger':'ghost'}" onclick="toggleTemp('${m.id}',${!isTemp(m)})">${isTemp(m)?'해제':'임시 지정'}</button></div>`).join('')||'<div class="empty">지정 가능한 참석 회원이 없습니다.</div>'}</div>`;if(versionCard)versionCard.insertAdjacentHTML('beforebegin',html);else box.insertAdjacentHTML('beforeend',html)}if((me?.globalAdmin||me?.role==='manager')&&!box.querySelector('.rosterReset60')){const versionCard=[...box.querySelectorAll(':scope > .card')].find(c=>(c.textContent||'').includes('프로그램 버전')),html=`<div class="card rosterReset60"><b>회원정보 전체 정리 초기화</b><div class="warn" style="margin:7px 0 10px;line-height:1.6">현재 모임에서 총관리자·모임관리자를 남기고 게임편성자·일반회원·게스트와 게임·대기·누적기록을 정리합니다.</div><button class="btn danger" style="width:100%" onclick="resetRoster60()">현재 모임 회원정보 전체 정리</button><div class="meta" style="margin-top:7px">권한: 모임관리자 · 총관리자</div></div>`;if(versionCard)versionCard.insertAdjacentHTML('beforebegin',html);else box.insertAdjacentHTML('beforeend',html)}[...box.querySelectorAll('.meta')].forEach(el=>{if((el.textContent||'').includes('콕매치 v59'))el.textContent='콕매치 v60 · 역할별 권한체계 재정비 · 전체회원 상태관리'})};
window.resetRoster60=async function(){if(!(me?.globalAdmin||me?.role==='manager'))return alert('모임관리자 이상 권한이 필요합니다.');const pin=prompt(`${me?.globalAdmin?'총관리자':'모임관리자'} PIN을 입력해주세요.`);if(pin===null||!pin.trim())return;if(!confirm(`${group?.name||'현재 모임'}의 회원정보를 전체 정리하시겠습니까?\n총관리자와 모임관리자는 유지됩니다.`))return;try{const x=await v60Request('reset_roster',{pin:pin.trim()});S=x.data;normalizeClient();renderAll();alert(`회원정보 정리 완료 · 삭제 ${Number(x.removedCount)||0}명`)}catch(e){showError(e)}};
if(location.pathname.startsWith('/launch/v60'))history.replaceState(null,'','/?loaded=60');if(me)renderAll();
})();
